root: true
parserOptions:
  parser: '@babel/eslint-parser'
env:
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:jest/recommended
  - plugin:promise/recommended
